services:
  - type: web
    name: google-sheets-mcp-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GOOGLE_CREDENTIALS
        sync: false
      - key: PORT
        value: 10000
    autoDeploy: true
    healthCheckPath: /
    domains:
      - google-sheets-mcp.onrender.com

